apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  version: 4.10.0
  valuesContent: |
    controller:
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
      extraArgs:
        enable-ssl-passthrough: "true"