apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }} 
    metadata:
      labels:
        app: {{ .Values.deploymentName }} 
    spec:
      containers:
      - name: debug-pod
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sleep", "infinity"] 
        ports:
        - containerPort: {{ .Values.service.targetPort }} 
