apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: registry-storage
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default "registry-pvc" }}
