apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
{{- if .Values.nodePortService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodePortService.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.nodePortService.type }}
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: {{ .Values.nodePortService.port }}
      targetPort: {{ .Values.nodePortService.port }}
      nodePort: {{ .Values.nodePortService.nodePort }}
{{- end }}
