apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-config
  namespace: reverse-proxy
data:
  nginx.conf: |
    events {}

    http {
      upstream prod {
        #server ingress-nginx-controller.ingress-nginx.svc.cluster.local:80;
        server 192.168.2.11:80;
      }

      upstream staging {
        server 192.168.2.16:80;
      }

      server {
        listen 443 ssl;
        server_name hquarter.app tekton.hquarter.app;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          proxy_pass http://prod;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name staging.hquarter.app tekton-stg.hquarter.app;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          proxy_pass http://staging;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
