apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse
  namespace: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse
  template:
    metadata:
      labels:
        app: nginx-reverse
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 443
              hostPort: 8443
              protocol: TCP
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: nginx-reverse-config
        - name: certs
          secret:
            secretName: hquarter-wildcard-tls
