apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobName }}
spec:
  template:
    spec:
      containers:
      - name: ai-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Never
  backoffLimit: {{ .Values.backoffLimit }}
