apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-registry-access
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: ["pods", "secrets"]
  verbs: ["get", "list", "watch"] # Required for Kaniko to read secrets if any
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"] # Required for logging build progress
- apiGroups: [""]
  resources: ["pods/exec"] # For debugging / if remote shell access is needed
  verbs: ["create"]
- apiGroups: ["tekton.dev"]
  resources: ["taskruns", "pipelineruns", "tasks", "pipelines"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # For Tekton resources

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-registry-access-binding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-registry-access
  apiGroup: rbac.authorization.k8s.io
