# ~/devops-hq-eh/tekton/04-trigger-template.yaml
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ai-agent-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      description: The URL of the Git repository
      default: 'git@github.com:ECHagedorn/devops-hq-eh.git'
    - name: repo-revision
      description: The Git revision (branch, tag, or commit SHA)
      default: ai-1
    - name: git-commit-sha
      description: The full commit SHA of the pushed code
    - name: pipeline-name
      description: The name of the pipeline to trigger
      default: build-deploy-microservice-pipeline
    - name: image-url
      description: image URL to build
      default: "192.168.2.11:32594/ai-agent"
    - name: dockerfile-path
      description: Path to Dockerfile
      default: Dockerfile
    - name: context-path
      description: Build context path
      default: .
    - name: chart-relative-path
      description: Path to Helm chart
      default: charts/ai-agent
    - name: release-name
      description: Helm release name
      default: ai-agent
    - name: target-namespace
      description: Namespace to deploy to
      default: devops-hq-eh

  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-debug-pipeline-run-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: build-deploy-microservice-pipeline
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: repo-url
            value: 'git@github.com:ECHagedorn/devops-hq-eh.git'
          - name: repo-revision
            value: 'ai-1'
          - name: image-url
            value: "192.168.2.11:32594/ai-agent:$(tt.params.git-commit-sha)"
          - name: dockerfile-path
            value: services/ai-agent/Dockerfile
          - name: context-path
            value: .
          - name: chart-relative-path
            value: manifests/helm/ai-agent
          - name: release-name
            value: ai-agent
          - name: target-namespace
            value: devops-hq-eh
          - name: smoke-url
            value: "" #"https://ai-agent.app/healthz"
