apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-push-event-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-controller
  triggers:
    - name: build-push-deploy-debug-pod
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/master' && body.head_commit.modified.exists(x, x.startsWith('services/debug-pod/')) || body.head_commit.modified.exists(x, x.startsWith('manifests/helm/debug-pod/')))"
      bindings:
        - ref: git-push-trigger-binding
      template:
        ref: debug-pod-trigger-template
    - name: build-push-deploy-hquarter
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/master' && body.head_commit.modified.exists(x, x.startsWith('services/hquarter/')) || body.head_commit.modified.exists(x, x.startsWith('manifests/helm/hquarter/')))"
      bindings:
        - ref: git-push-trigger-binding
      template:
        ref: hquarter-trigger-template
    - name: build-push-deploy-ai-agent
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/ai-agent' && (body.head_commit.modified.exists(x, x.startsWith('manifests/helm/ai-agent/')) || body.head_commit.modified.exists(x, x.startsWith('manifests/helm/ai-agent/')))"
      bindings:
        - ref: git-push-trigger-binding
      template:
        ref: ai-agent-trigger-template