apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hquarter-app-cert
  namespace: default
spec:
  secretName: hquarter-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hquarter.app
  dnsNames:
    - hquarter.app
