image:
  tag: "1.27.5"

ports:
  http: 8080
  https: 8443

upstreams:
  prod: "192.168.2.11:80"
  staging: "192.168.2.16:80"

domains:
  common: "hquarter.app"
  prod:
    - "hquarter.app"
    - "tekton.hquarter.app"
  staging:
    - "staging.hquarter.app"
    - "tekton-stg.hquarter.app"

tls:
  secretName: hquarter-wildcard-tls
  issuer:
    name: letsencrypt-gcp
    kind: ClusterIssuer
