apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm-install-ingress-nginx-canary
  namespace: tekton-pipelines
spec:
  params:
    - name: chartVersion
      type: string
      default: 4.10.0
  workspaces:
    - name: kubeconfig-dir
  steps:
    - name: install-canary-ingress
      image: alpine/helm:3.14.0
      script: |
        #!/bin/sh
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx-canary ingress-nginx/ingress-nginx \
          --version $(params.chartVersion) \
          --namespace ingress-nginx-canary \
          --create-namespace \
          --set controller.ingressClassResource.name=nginx-canary \
          --set controller.ingressClassResource.enabled=true \
          --set controller.replicaCount=1 \
          --set controller.service.type=ClusterIP \
          --atomic \
          --timeout 300s
      env:
        - name: KUBECONFIG
          value: /workspace/kubeconfig-dir/config