apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {}

    http {
      upstream prod {
        server {{ .Values.upstreams.prod }};
      }

      upstream staging {
        server {{ .Values.upstreams.staging }};
      }

      server {
        listen 443 ssl;
        server_name {{ .Values.domains.prod | join " " }};

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          proxy_pass http://prod;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      server {
        listen 443 ssl;
        server_name {{ .Values.domains.staging | join " " }};

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
          proxy_pass http://staging;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

