#!/bin/bash
set -e

echo "🔧 Patching services/ai-agent/main.py for REPL input..."
cat > services/ai-agent/ai_agent/main.py <<EOF
import os
import sys
from ai_agent.url_fetcher import fetch_url
from ai_agent.classifier import classify_page
from ai_agent.analyzer import analyze_page
from ai_agent.planner import plan_action
from ai_agent.executor import execute_plan
from ai_agent.utils import print_disclaimer

def agent_repl():
    print("🟢 AI Agent is live. Type a URL to analyze or 'exit' to quit.")
    while True:
        url = input("🌐 URL> ").strip()
        if url.lower() == "exit":
            print("👋 Exiting.")
            break
        if not url.startswith("http"):
            print("❌ Invalid URL. Try again.")
            continue

        response = fetch_url(url)
        if not response:
            print("❌ Failed to fetch URL.")
            continue

        page_type = classify_page(response)
        intent = analyze_page(url, response)
        plan = plan_action(page_type, intent)
        result = execute_plan(plan)

        print("\\n🔍 Classification:", page_type)
        print("🧠 Intent:", intent)
        print("🗺️ Plan:", plan)
        print("📦 Result:", result)
        print_disclaimer()

if __name__ == "__main__":
    agent_repl()
EOF

echo "✅ Patched services/ai-agent/ai_agent/main.py"

echo "🛠 Updating Dockerfile..."
cat > services/ai-agent/Dockerfile <<EOF
FROM python:3.10-slim

WORKDIR /app
COPY ai_agent/ ai_agent/
COPY ai_agent/main.py .

RUN pip install requests

CMD ["python", "main.py"]
EOF

echo "✅ Updated Dockerfile to support REPL"

echo "🧱 Converting Helm Job → Deployment..."

cat > manifests/helm/ai-agent/templates/deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        stdin: true
        tty: true
      restartPolicy: Always
EOF

cat > manifests/helm/ai-agent/values.yaml <<EOF
deploymentName: ai-agent

image:
  repository: "192.168.2.11:32594/ai-agent"
  tag: "latest"
  pullPolicy: IfNotPresent
EOF

# Optional: remove old job template
rm -f manifests/helm/ai-agent/templates/job.yaml

echo "✅ Converted to interactive deployment"
echo "🚀 Run: helm upgrade --install ai-agent manifests/helm/ai-agent"

