replicaCount: 1
deploymentName: debug-pod
namespace: devops-hq-eh

image:
  repository: 192.168.2.11:32594/debug-pod
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

serviceAccount:
  # If set, use this value as serviceAccount name, otherwise defaults to <deploymentName>-sa
  name: ""
