replicaCount: 1
deploymentName: hquarter

image:
  repository: 192.168.2.11:32594/hquarter
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

ingress:
  enabled: false
