# HqUARTER helm chart
#
replicaCount: 1
deploymentName: hquarter
namespace: devops-hq-eh

image:
  repository: 192.168.2.11:32594/hquarter
  pullPolicy: Always
  tag: "latest"

service:
  name: hquarter
  type: ClusterIP
  port: 5000
  targetPort: 5000
    #nodePort: 30080

ingress:
  enabled: true
  name: hquarter-ingress
  host: hquarter.app
  tlsSecret: hquarter-tls
  clusterIssuer: letsencrypt-prod
  ssl-redirect: false
    # false because of reverse proxy ssl termination
serviceAccount:
  # If set, use this value as serviceAccount name, otherwise defaults to <deploymentName>-sa
  name: ""
