# HqUARTER helm chart
#
replicaCount: 1
deploymentName: hquarter
namespace: devops-hq-eh

image:
  repository: 192.168.2.11:32594/hquarter
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
    #nodePort: 30080

ingress:
  enabled: false

serviceAccount:
  # If set, use this value as serviceAccount name, otherwise defaults to <deploymentName>-sa
  name: ""
