apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-devops-hq-eh-access
  namespace: devops-hq-eh
rules:
  - apiGroups: [""]
    resources: ["pods", "serviceaccounts", "services", "services/finalizers", "endpoints", "persistentvolumeclaims", "configmaps", "secrets", "events"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments"]
    verbs: ["get", "list", "watch"]
  # For Helm v2 (Tiller) or Helm v3 release storage
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-namespace-creator
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-namespace-creator-binding
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: tekton-pipelines
  - kind: ServiceAccount
    name: default
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-namespace-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-devops-hq-eh-access-binding
  namespace: devops-hq-eh
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: tekton-pipelines
- kind: ServiceAccount
  name: default
  namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-devops-hq-eh-access
  apiGroup: rbac.authorization.k8s.io
